### ISSUE TITLE
Incorrect zally-api.yaml 

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#201]
```
definitions:
  LintingRequest:
    type: object
    description: Request containing a swagger definition file
    properties:
      api_defintion:
        type: object
```

 - typo in field name `api_definition`
 - wrong type for this field: this should be a string, not an object.
