### ISSUE TITLE
`x-zally-ignore`: explanation must be mandatory for each ignored rule

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#754]
Currently, `x-zally-ignore` extension accepts a set of `RuleId`s to be ignored. This is a great feature, but we have to assure the correct usage of it. Let's begin with understanding the behaviour of the users.

We want the API designers to explicitly **state a reason** why the desicion has been made to ignore the rule. Therefore, the interface has to change from:

```
x-zally-ignore:
  type: array
  items:
    type: string
```

to

```
x-zally-ignore:
  type: array
  items:
    type: object
    required:
      - rule_id
      - reason
    properties:
      rule_id:
        type: string
      reason:
        type: string
```

# Acceptance criteria

- [ ] Rules are not deactivated if no reason provided
- [ ] RESTful API is adjusted (reason is mandatory)
- [ ] New check is implemented which creates violations if reason is not provided (a `MUST` violation, can be linked to Zalando rule 100: https://opensource.zalando.com/restful-api-guidelines/#100)
